### ISSUE TITLE
multiiple "split problem" sets

### ISSUE THREAD

**Issue by LorenzoRinaldi** [pyESM-project/pyesm#57]
When defining a model with multiple sets characterized by "split_problem == True", it is necessary to define all these sets among the coordinates of all the variables, even if some variables are not dependent on those sets.

**Comment by Mast86** [comment]
solved: now if a variable is not defined for set-split problem, provided that the variable is unique, it is allowed to use it in all problems defined by the different sets-split problem. this way, for example, technical coefficients can be defined as equal in all scenarios without repeating them several times.
