### ISSUE TITLE
defining two "identical" sets 

### ISSUE THREAD

**Issue by LorenzoRinaldi** [pyESM-project/pyesm#58]
Our models often require to define the same set on both rows and columns of a variable. This is compatible with 2d matrices but not for 1d tabular database like SQL, which they require different names for each column.

It would be nice to be able to add a property of a set, where you can define it equal to another one. The user would just provide one.
Example:

 flows_from:
    symbol: flows_from   
    table_name: _set_FLOWS_FROM 
    equal_to: **flows_to**
    table_structure:
        name: [ff_Names, TEXT]

**Comment by Mast86** [comment]
done. You can now indicate in the parameter "copy_from" the name of the set to be copied. Remember you have still to indicate the structure of the set (headers names must be different with respect to the mirrored set).
