### ISSUE TITLE
Type error when loading model data

### ISSUE THREAD

**Issue by valebii** [pyESM-project/pyesm#62]
When loading data inputs into database add check that verifies that  all input_data.xlsx cells have been filled, to avoid error (as empty cells are read as strings): 

"**TypeError**: unsupported operand type(s) for -: 'str' and 'str'"

**Comment by Mast86** [comment]
Improving Model.Core.data_tocvxpy_exogenous_vars() method by checking allowed values type in source data before assign them to variables. Allowed types for values defined in Constants. Issue solved. Working with all integration unit tests.
