### ISSUE TITLE
Definition order of aggregated sets generates wrong identity_rcot

### ISSUE THREAD

**Issue by CamiCit** [pyESM-project/pyesm#74]
When defining a set as an aggregation of another one, the definition of the aggregated set must happen in the same order in which it appears next to the set to be aggregated. 
This generates errors if the definition doesn't follow the order: the identity_rcot is built following the order in which the aggregated items appear in the defining Excel sheet, instead of the order in which they are listed next to the definition of the non-aggregated item. 

Example: 
flows={HP_HW,HP_cold,Rad_heat,AC_cold}
flows_agg={HW,Heat,Cold}
So the identity_rcot matrix Flows_agg x Flows is built connecting: 
(HP_HW,HW) (HP_cold,Heat) (Rad_heat,Cold) (AC_cold,Heat)

while it should be
(HP_HW,HW) (HP_cold,Cold) (Rad_heat,Heat) (AC_cold,Cold)

**Comment by Mast86** [comment]
I have fixed the issue. 
Actions: 
- Improving util_funtions.identity_rcot() to handle the case where set labels for rows and columns are ordered differently with respect to the variable.related_dims_map dataframe. 
- Tests expanded and modified accordingly. Set file of the feature/constant test case modified to reflect this case.
